"""**TradingFlow** is a lightweight library for quantitative investment
research that supports multi-frequency market data, formulaic factors,
forecasting models, portfolio optimization methods and backtesting in a
unified data model.

Main design goals:

- **Composable modules:** trading strategies are computation graphs, whose
  nodes are either data sources or operators. Common sources and operators
  are provided out of the box, and new ones can be readily implemented in
  either Rust or Python.
- **Agent-friendly codebase:** code-documentation consistency and a hierarchy
  of documented modules is maintained to facilitate LLM code exploration and
  generation. When using LLM coding agents (Claude Code, Codex, OpenCode, etc.),
  start every session by instructing the agent to read [AGENTS.md](AGENTS.md)
  and then describe your tasks.

# Get started

Prerequisites: Python 3.12+ and a stable Rust toolchain
([rustup.rs](https://rustup.rs)).

Build commands:

```bash
git clone https://github.com/bridgekat/tradingflow.git
cd tradingflow
pip install -e ".[dev]"
```

TradingFlow uses [Maturin](https://www.maturin.rs/) to automatically compile
the Rust core and install the Python package during the `pip install` step.

# Usage

Below is a tiny example that records a synthetic price series and prints its
tail. It illustrates the three things you do in every program: create a
[`Scenario`][tradingflow.scenario.Scenario], register sources and operators, then
invoke `run()`.

```python
import numpy as np
import tradingflow as tf

# Example data: 3 months of daily prices generated by a random walk.
timestamps = np.arange("2024-01-01", "2024-04-01", dtype="datetime64[D]")
values = np.random.randn(len(timestamps)).cumsum() + 100.0

# Create a scenario, which stores the computation graph.
sc = tf.Scenario()

# Create a source which feeds timestamped values into the graph.
prices = sc.add_source(tf.sources.ArraySource(timestamps, values, dtype=np.float64))

# Create an operator which transforms or accumulates values from upstream nodes.
# The `Record` operator collects every value of `prices` into a time series.
history = sc.add_operator(tf.operators.Record(prices))

# The `RollingMean` operator reduces a series to the mean of its last-N window,
# emitting a new array snapshot each time the upstream series grows.
ma = sc.add_operator(tf.operators.rolling.RollingMean(history, window=10))

# Record the rolling-mean snapshots back into a series so the full history
# is available for inspection after the run.
ma_history = sc.add_operator(tf.operators.Record(ma))

# Run the event loop until all sources are exhausted.
sc.run()

# Inspect the results via `series_view()`, which returns a `SeriesView` that can be converted to a Pandas `Series`.
print(sc.series_view(ma_history).to_series().tail())
```

The resulting computation graph:

```mermaid
flowchart LR
    start(( )):::hidden
    prices(["Array<br/><code>prices</code>"]):::array
    history(["Series<br/><code>history</code>"]):::series
    ma(["Array<br/><code>ma</code>"]):::array
    ma_history(["Series<br/><code>ma_history</code>"]):::series
    start -- ArraySource --> prices
    prices -- Record --> history
    history -- "RollingMean(window=10)" --> ma
    ma -- Record --> ma_history
    classDef hidden fill:#fff,stroke:#fff,color:#fff
    classDef array fill:#e6f2ff,stroke:#3b82f6,color:#1e3a8a
    classDef series fill:#f5f5f5,stroke:#6b7280,color:#111827
```

# Core concepts

## Arrays and series

When using the Python wrapper, every node in the graph can hold one of two
types of value[^1] or choose to hold no value at all:

- An **array** is a fixed-shape NumPy-like tensor — the current
  *snapshot* of something.  For example, today's closing price for
  every instrument in the universe is one array of shape `(N,)`; a
  covariance matrix is an array of shape `(N, N)`.  Arrays are updated
  in place every time the node's operator produces.
- A **series** is the *full history* of array values written into it,
  with a parallel vector of timestamps.  Series are what you inspect
  at the end of a run (typically via
  [`Scenario.series_view`][tradingflow.scenario.Scenario.series_view] → pandas).

The following operators can be used to convert between them:

- [`Record`][tradingflow.operators.record.Record] — append every upstream
  array value into a series (array → series).
- [`Last`][tradingflow.operators.last.Last] — expose the most recent series
  value as an array (series → array).

Under the hood, both arrays and series are backed by contiguous `Vec<T>`
buffers on the Rust side. To prevent dangling points, data is copied when being
read from the Python side.

## Sources

A **source** is a node that produces timestamped values from somewhere
outside the graph.  Conceptually it is a pair of async iterators: a
*historical* stream (replayed as fast as possible at run start) and a
*live* stream (merged in in real time).  Either may be empty — most
backtests only use the historical one.

Typical sources are raw market data feeds or pre-computed factors —
snapshot prices, financial reports, order flows — plus unit-valued
**clocks** that just *tick* on a schedule.

See [`tradingflow.sources`][tradingflow.sources] for the full catalog
of built-in sources.

## Operators

An **operator** is a node that reads from one or more upstream nodes
and writes to its own output node.  Its `compute()` method is called
every time an upstream node produces, receives references to input and
output data, and decides whether to propagate the notification further
downstream.

See [`tradingflow.operators`][tradingflow.operators] for the full
catalog — structural glue, numeric operators, rolling windows,
predictors, portfolios, traders, metrics, and stock-specific helpers.

## Scenarios

A [`Scenario`][tradingflow.scenario.Scenario] owns the acyclic computation graph
plus the event loop that drives it.
[`Scenario.run`][tradingflow.scenario.Scenario.run] drains every source (first
the historical streams, then the live ones) in timestamp order,
**coalesces** events that share the same timestamp into a single *flush
batch*, and propagates each batch through the graph in topological order.
This guarantees that within a batch every operator sees a consistent
cross-section of its inputs, and that successive batches have strictly
increasing timestamps.

The typed handles returned by
[`add_source`][tradingflow.scenario.Scenario.add_source] and
[`add_operator`][tradingflow.scenario.Scenario.add_operator] encode both the
node's shape and its value kind (array vs. series), so wiring errors
are caught before the event loop starts.

# Notes

## Timestamp conventions

TradingFlow uses **TAI (International Atomic Time)** throughout.
Timestamps represent the number of SI nanoseconds since
`1970-01-01 00:00:00 TAI`, which is exactly 37 seconds before the Unix epoch
`1970-01-01 00:00:00 UTC`. The reason of this is to have a rigorous semantics
for timestamp arithmetic: every calendar day is 86400 SI seconds, and `b - a`
yields true elapsed time with no "hidden" leap seconds. On the Rust side,
the `Instant` type is used to represent timestamps. On the Python side,
`numpy.datetime64[ns]` is used.

If incoming data contains UTC timestamps, or when output data is resolved as
UTC timestamps, use the conversion helpers in
[`tradingflow.data.time`][tradingflow.data.time]:

- [`utc_to_tai`][tradingflow.data.time.utc_to_tai] — accepts a scalar
  or NumPy array, adds the current TAI-UTC offset.
- [`tai_to_utc`][tradingflow.data.time.tai_to_utc] — the inverse.

String-parsing sources ([`CSVSource`][tradingflow.sources.csv_source.CSVSource],
[`FinancialReportSource`][tradingflow.sources.stocks.financial_report_source.FinancialReportSource])
accept an `is_utc` flag (default `True`) and a `tz_offset: np.timedelta64`
parameter to provide TAI-UTC conversion and basic time zone adjustment.

## Notification semantics

When a source or operator emits a new value, every downstream operator is
scheduled for execution.  Each downstream operator receives a flat
`produced: tuple[bool, ...]` mask, parallel to its inputs, reporting *which*
of them produced new output in the current flush.  This allows for two
different mental models to be implemented:

### Time-series model

We can consider an operator as a time series which changes its value over time.
The operator produces a new value to signify a change.  In this case,
its latest value can be read regardless of whether it has produced a new value
in the current flush.  Its initial value then represents the state before the
first value is produced.

This is the natural model for state that persists over time: prices,
positions...  Most built-in operators follow this pattern
and ignore the `produced` mask entirely.

### Message-passing model

We can also consider an operator as a message queue. The operator produces a
new value to signify a new message that needs to be processed.  In this case,
its value should be read only when its `produced` flag is `True`, to avoid
processing the same stale message multiple times.  Its initial
value then has no particular meaning, because it is never read.

This can be used when "a lack of new value" is interpreted differently than
"keeping the previous value unchanged".  For example,
[`StackSync`][tradingflow.operators.stack.StackSync] and
[`ConcatSync`][tradingflow.operators.concat.ConcatSync] are the message-
passing counterparts of [`Stack`][tradingflow.operators.stack.Stack] and
[`Concat`][tradingflow.operators.concat.Concat], filling all non-produced input
slots with `NaN`.  They can be used to merge daily prices of individual stocks
into a single array, where *the absence of a new price for a stock on a given
day* is meaningfully different from *the price for the stock is the same as in
the previous day*.

Whether a source or operator follows the time-series model or the
message-passing model is a design choice that should be documented in its
docstring.

# Where to go next

- **Runtime:** [`Scenario`][tradingflow.scenario.Scenario] — the computation graph and its event loop.
- **Extension bases:** [`Source`][tradingflow.source.Source] / [`Operator`][tradingflow.operator.Operator] for Python implementations, [`NativeSource`][tradingflow.source.NativeSource] / [`NativeOperator`][tradingflow.operator.NativeOperator] for Rust-backed descriptors.
- **Built-in catalogs:** [`tradingflow.sources`][tradingflow.sources] and [`tradingflow.operators`][tradingflow.operators].
- **Types, handles, and views:** [`tradingflow.data`][tradingflow.data].
- **Utilities:** [`tradingflow.utils`][tradingflow.utils].

[^1]: The Rust core supports an arbitrary type, but only these are exposed
across the Python interface for now.  We might support arbitrary Python objects
in the future.
"""

from .data import Array, ArrayView, Handle, NodeKind, Series, SeriesView, Unit
from .source import Source, NativeSource
from .operator import Operator, NativeOperator
from .scenario import Scenario
from .utils import Schema

from . import data
from . import sources
from . import operators
from . import utils


__all__ = [
    "ArrayView",
    "SeriesView",
    "Source",
    "Operator",
    "NativeSource",
    "NativeOperator",
    "Scenario",
    "NodeKind",
    "Handle",
    "Array",
    "Series",
    "Unit",
    "Schema",
    "data",
    "sources",
    "operators",
    "utils",
]
